version: '3.8'

services:
  backend:
    build:
      context: ./backen
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - http://backend:8000
    depends_on:
      - backend